# Generated by Django 5.2.7 on 2025-10-16 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('type', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('doing', 'In Arbeit'), ('done', 'Erledigt')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assignee', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
