# Generated by Django 5.2.7 on 2025-10-16 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('intro', models.TextField(blank=True)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('tools', models.ManyToManyField(blank=True, related_name='comparisons', to='catalog.tool')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.tool')),
            ],
        ),
    ]
