# Generated by Django 5.2.7 on 2025-10-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_normalize_score_breakdown'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comparison',
            options={'verbose_name': 'Vergleich', 'verbose_name_plural': 'Vergleiche'},
        ),
    ]
