# Generated by Django 5.2.7 on 2025-10-16 19:14

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('vendor', models.CharField(blank=True, max_length=160)),
                ('short_desc', models.CharField(blank=True, max_length=240)),
                ('long_desc', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('language_support', models.JSONField(default=list)),
                ('pricing_model', models.CharField(blank=True, max_length=80)),
                ('free_tier', models.BooleanField(default=False)),
                ('monthly_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='tools', to='catalog.category')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price_month', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_year', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='catalog.tool')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(blank=True, max_length=120)),
                ('program_url', models.URLField(blank=True)),
                ('commission_type', models.CharField(choices=[('flat', 'Pauschal'), ('percent', '% vom Umsatz'), ('recurring', 'Wiederkehrend')], default='percent', max_length=20)),
                ('commission_value', models.CharField(blank=True, max_length=60)),
                ('cookie_days', models.IntegerField(default=30)),
                ('tracking_note', models.CharField(blank=True, max_length=240)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliates', to='catalog.tool')),
            ],
        ),
    ]
