# Generated by Django 5.2.7 on 2025-10-16 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
