# Generated by Django 5.2.7 on 2025-10-16 19:14

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=240)),
                ('body', models.TextField()),
                ('reading_time', models.PositiveIntegerField(default=5)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='guides/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='catalog.category')),
                ('related_tools', models.ManyToManyField(blank=True, to='catalog.tool')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField()),
                ('use_case', models.CharField(blank=True, max_length=160)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('tools', models.ManyToManyField(blank=True, to='catalog.tool')),
            ],
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('persona', models.CharField(max_length=120)),
                ('problem', models.TextField()),
                ('workflow_steps', models.JSONField(blank=True, default=list)),
                ('kpi_impact', models.JSONField(blank=True, default=dict)),
                ('tools', models.ManyToManyField(blank=True, to='catalog.tool')),
            ],
        ),
    ]
