# Generated by Django 5.2.7 on 2025-10-18 08:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={},
        ),
        migrations.AddField(
            model_name='guide',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guide',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Veröffentlicht')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='guide',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prompt',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prompt',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Veröffentlicht')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='prompt',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usecase',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usecase',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Veröffentlicht')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='usecase',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='guide',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
